[package]
name = "ascii_3d"
version = "0.1.0"
authors = ["abdel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.19.0"
bresenham = "0.1.1"
cgmath = "0.18.0"